import Head from "next/head";
import NextLink from "next/link";
import Link from "next/link";
import { ChakraProvider } from "@chakra-ui/react"
import { MDXProvider } from "@mdx-js/react";
import { MDXComponents } from '../components/mdx-components';

import { Fonts } from '../styles/fonts.styles';
import { theme } from '../styles/theme.styles';

const MyApp = ({ Component, pageProps }) => (
	<>
		<Head>
			<title>Monorepo Style Guide xxzxx</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<ChakraProvider theme={theme}>
			<Fonts />
			<MDXProvider components={MDXComponents}>
				<div>
					<NextLink href={'/'}><h1>Monorepo Style Guide</h1></NextLink>
					<p>Which scenario best describes your use case?</p>
					<ul>
						<li><Link href="/scenario/product"><a>I want to build an app</a></Link></li>
						<li><Link href="/scenario/product-and-design-system"><a>I want to build an app with a design system</a></Link></li>
						<li><Link href="/scenario/publish-packages"><a>I want to use packages outside of the monorepo</a></Link></li>
						<li><Link href="/scenario/open-source-library"><a>I want to build an open source library</a></Link></li>
						<li><Link href="/scenario/bring-apps"><a>I want to bring existing packages in to a monorepo</a></Link></li>
					</ul>
					<br/>
					<Component {...pageProps} />
				</div>
			</MDXProvider>
		</ChakraProvider>
	</>
);

export default MyApp;
