import Head from "next/head";
import { ChakraProvider } from "@chakra-ui/react"
import { MDXProvider } from "@mdx-js/react";
import { MDXComponents } from '../components/mdx-components';
import { AppLayout } from '../components/app-layout';

import { Fonts } from '../styles/fonts.styles';
import { theme } from '../styles/theme.styles';

const MyApp = ({ Component, pageProps }) => {
	return (
		<>
			<Head>
				<title>Monorepo Style Guide</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<style>
					{`
					  html,
						body,
					  body + div,
					  body + div + div { height: 100% }
					`}
				</style>
			</Head>
			<ChakraProvider theme={theme}>
				<Fonts />
				<MDXProvider components={MDXComponents}>
					<AppLayout>
						<Component {...pageProps} />
					</AppLayout>
				</MDXProvider>
			</ChakraProvider>
		</>
	);
}

export default MyApp;
